project:
  type: website
    
website:
  site-url: https://www.terralid.org
  repo-url: https://github.com/terralid/website
  description: "TerraLID is a digital research data infrastructure for lead isotope data in archaeology and develops next-generation tools for the archaeological sciences."
  favicon: 'assets/favicon/favicon.ico'
  navbar:
    logo: assets/TerraLID_logo_word_white.png
    logo-alt: "TerraLID logo"
    left:
      - text: "  "
      - text: "Products"
        menu:
          - href: https://metadata.terralid.org
            text: "Metadata profile"
          - href: https://edu.terralid.org
            text: "Textbook"
      - text: "  "  
      - blog.qmd
      - team.qmd
      - vision.qmd
      - network.qmd
      - resources.qmd
      - text: "  "
      - text: "Events"
        menu: 
          - events-current.qmd
          - events-archive.qmd
      - text: "Meet us"
        href: meet-us.qmd
      - text: "  "
      - text: "Prototypes (GlobaLID)"
        menu: 
          - icon: box-arrow-up-right
            href: https://archmetaldbm.github.io/Globalid/
            text: "Webpage"
          - icon: box-arrow-up-right
            href: https://globalid.dmt-lb.de/
            text: "Web App"
          - icon: box-arrow-up-right
            href: https://github.com/archmetalDBM/GlobaLID-database
            text: "Database"
#    right: 
#      - icon: box-arrow-up-right
#        href: https://edu.terralid.org
#        text: "Textbook"
#      - text: "  "
#      - text: "  "
    tools:
      - icon: envelope-fill
        href: mailto:terralid@bergbaumuseum.de?subject=TerraLID
      - icon: github
        href: https://github.com/terralid
      - icon: rss
        href: blog.xml
  page-footer: 
    left: |
      Last updated: {{< meta date >}} <br> 
      [Legal information](/about.qmd) <br> 
      <br>
      Built with <a href='https://quarto.org/'>Quarto</a>.
    center: | 
      Coordinated and hosted by:
      
      ::: {width=800 layout="[ 70 , 30 ]"}
      ::: {#column-empty}
      
      ![](https://www.bergbaumuseum.de/fileadmin/files/header/Logo_Bergbaumuseum_4c.svg){fig-alt="Logo of the Deutsches Bergbau-Museum Bochum"}
      
      :::
      :::  {#column-empty}
      
      ![](https://www.bergbaumuseum.de/fileadmin/files/footer/Logos/DMT.svg){fig-alt="Logo of the DMT-LB"}
      
      :::
      :::
    
    right: |
      
      ::: {style="text-align: center"}
      Funded by:  
      
      ![](assets/dfg_logo_footer.gif){height=69px fig-alt="Logo of the German Research Foundation"}
      :::


format:
  html:
    theme: 
      - sandstone
      - custom.scss
    css: styles.css
    toc: true
    toc-location: left
    link-external-newwindow: true
    date: today
    email-obfuscation: javascript
    template-partials:
      - title-block.html
    margin-header: |
      ::: {.callout-tip title="TerraLID Mailling list" icon=false}
      You want to receive about quarterly updates on TerraLID and related topics?  
      [Subscribe to our mailing list!](https://www.listserv.dfn.de/sympa/subscribe/terralid-news)
      :::
      ::: {.callout-tip title="Contact" icon=false}
      Questions about TerraLID? [TerraLID [at] bergbaumuseum.de](mailto:terralid@bergbaumuseum.de?subject=Info about TerraLID)
      :::
      ::: {.callout-warning title="Quicklinks" icon=false}
      [Metadata profile]()  
      [Textbook]()
      :::

resources:
  - CNAME

execute:
  freeze: auto
  