project:
  type: website
    
website:
  site-url: https://www.terralid.org
  repo-url: https://github.com/terralid/website
  description: "TerraLID is a digital research data infrastructure for lead isotope data in archaeology and develops next-generation tools for the archaeological sciences."
  favicon: 'assets/favicon/favicon.ico'
  navbar:
    logo: assets/TerraLID_logo_word_white.png
    logo-alt: "TerraLID logo"
    left:
      - href: index.qmd
        text: "Home"
      - blog.qmd
      - href: team.qmd
        text: "Team"
      - text: "Workshops"
        menu: 
          - workshop-current.qmd
          - workshop-archive.qmd
      - events.qmd
      - icon: box-arrow-up-right
        href: https://globalid.dmt-lb.de/
        text: "Web App"
      - icon: box-arrow-up-right
        href: https://github.com/archmetalDBM/GlobaLID-database
        text: "Database"
    tools:
      - icon: envelope-fill
        href: mailto:terralid@bergbaumuseum.de?subject=TerraLID
      - icon: github
        href: https://github.com/terralid
      - icon: rss
        href: blog.xml
  page-footer: 
    left: "Test"
    right: 
      - text: "Legal information"
        href: about.qmd
  

format:
  html:
    theme: 
      - sandstone
      - custom.scss
    css: styles.css
    toc: true
    toc-location: left
    link-external-newwindow: true

execute:
  freeze: auto
  