project:
  type: website
    
website:
  site-url: https://www.terralid.org
  repo-url: https://github.com/terralid/website
  description: "TerraLID is a digital research data infrastructure for lead isotope data in archaeology and develops next-generation tools for the archaeological sciences."
  favicon: 'assets/favicon/favicon.ico'
  navbar:
    logo: assets/TerraLID_logo_word_white.png
    logo-alt: "TerraLID logo"
    left:
      - href: index.qmd
        text: "Home"
      - blog.qmd
      - team.qmd
      - vision.qmd
      - network.qmd
      - resources.qmd
      - text: "  "
      - text: "Events"
        menu: 
          - events-current.qmd
          - events-archive.qmd
      - text: "Meet us"
        href: meet-us.qmd
      - text: "  "
      - text: "Prototypes (GlobaLID)"
        menu: 
          - icon: box-arrow-up-right
            href: https://archmetaldbm.github.io/Globalid/
            text: "Webpage"
          - icon: box-arrow-up-right
            href: https://globalid.dmt-lb.de/
            text: "Web App"
          - icon: box-arrow-up-right
            href: https://github.com/archmetalDBM/GlobaLID-database
            text: "Database"
#    right: 
#      - icon: box-arrow-up-right
#        href: https://edu.terralid.org
#        text: "Textbook"
#      - text: "  "
#      - text: "  "
    tools:
      - icon: envelope-fill
        href: mailto:terralid@bergbaumuseum.de?subject=TerraLID
      - icon: github
        href: https://github.com/terralid
      - icon: rss
        href: blog.xml
  page-footer: 
    left: 
      - text: "Built with <a href='https://quarto.org/'>Quarto</a>. <br> Last updated: {{< meta date >}}"
    center: | 
      Coordinated and hosted by: 
      
      ::: {layout="[ 70 , 30 ]"}
      ::: {#column-empty}
      
      ![](https://www.bergbaumuseum.de/fileadmin/files/header/Logo_Bergbaumuseum_4c.svg)
      
      :::
      :::  {#column-empty}
      
      ![](https://www.bergbaumuseum.de/fileadmin/files/footer/Logos/DMT.svg)
      
      :::
      :::
    
    right: 
      - text: "Legal information"
        href: about.qmd
  

format:
  html:
    theme: 
      - sandstone
      - custom.scss
    css: styles.css
    toc: true
    toc-location: left
    link-external-newwindow: true
    date: today
    email-obfuscation: javascript
    template-partials:
      - title-block.html

resources:
  - CNAME

execute:
  freeze: auto
  