---
title: "Meet us at... "
---

We are joining the meetings listed below, usually with a presentation about TerraLID. We are looking forward to meeting you there and chat with you!

Events organised and hosted by the TerraLID team are listed on our [events page](events-current.qmd). 

## Upcoming

* [International Symposium on the Metallurgy of the European Iron Age II (SMEIA II)](https://www.leiza.de/forschung/forschungsfelder/zusammenleben-in-komplexer-werdenden-sozialen-gefuegen/international-symposium-on-the-metallurgy-of-the-european-iron-age-ii-smeia-ii)
* [Young Researchers in Archaeometry 2025](https://www.yra-ecr.org/current.html)
* [NFDI4Objects: 3rd Community Meeting](https://www.nfdi4objects.net/news/n4o_news_20241212-0837/)
* [Geo4Göttingen](https://www.geo4goettingen2025.de/)
* [31^st^ Annual Meeting of the European Association of Archaeologists (EAA)](https://www.e-a-a.org/eaa2025/)
* [Goldschmidt 2025](https://conf.goldschmidt.info/goldschmidt/2025/meetingapp.cgi)

## 2025
* Archäometrie & Denkmalpflege

## 2024

* Scientific Forum Entangling Geosciences and Chemistry in Cameroon
* Young Researchers in Archaeometry 2024
* 84. Verbandstagung des Nordwestdeutschen Verbands für Altertumsforschung
* 30^th^ Annual Meeting of the European Association of Archaeologists (EAA)
* European Mineralogical Conference 2024
* Archaeometallurgy in Europe 2024
* 89^th^ Annual Meeting of the Society for American Archaeology

## 2023

* Research in Progress Meeting 2023-2 of the Historical Metallurgy Society
* Young Researchers in Archaeometry 2023
* 1^st^ Conference on Research Data Infrastructure (CoRDI)
* 29^th^ Annual Meeting of the European Association of the Archaeologists (EAA)
* NFDI4Earth Plenary
* Archäometrie & Denkmalpflege

## 2022

* GeoMinKöln
* Young Researchers in Archaeometry 5
* 28^th^ Annual Meeting of the European Association of the Archaeologists (EAA)
* 16^th^ PAA (PanAfrican Archaeological Association) Congress
* useR! 2022
* Advances in Isotope Ratio and related analyses for mapping migrations from Prehistory to the Viking Age (Joint Meeting of the Royal Society of Chemistry & Society of Antiquaries)
* 43^rd^ International Symposium on Archaeometry
* 3^rd^ International Congress on Archaeological Sciences in the Eastern Mediterranean and the Middle East (ICAS-EMME 3)
* Le plomb et ses questions analytiques

## 2021

* Historical Metallurgy Society: Research in Progress Meeting
* 3^rd^ European Mineralogical Conference
* Young Researchers in Archaeometry 4
