---
title: "Network"
---

The TerraLID team is actively involved in national and international initiatives that aim to improve research data management and literacy. 

## IGSN–DataCite Archaeology & Cultural Heritage Community of Practice
Jointly coordinated by IGSN e.V. and DataCite, the [IGSN–DataCite Archaeology & Cultural Heritage Community of Practice](https://ev.igsn.org/communities/archaeology) aims to promote the use of persistent identifiers in archaeology. In 2022, the community conducted a survey about current practices related to the use of persistent identifiers in archaeology. Since then, activities focused on the development of a metadata profile for archaeological and cultural heritage materials for IGSNs. IGSNs or **I**nternational **G**eneric **S**ample **N**umbers are persistent identifiers for physical objects. Similar to Digital Object Identifiers, or DOIs, for digital objects such as publications, [IGSN](https://ev.igsn.org/about-igsns)s make physical samples citable and provide informative metadata about them. This facilitates their (re-)use, improve data sharing and increase the visibility of samples. Because what communities consider as relevant metadata about a sample differs, community-specific metadata profiles for IGSNs are needed for the optimal description of physical objects. TerraLID will align object- and site-related metadata with the metadata profile developed by the IGSN–DataCite Archaeology & Cultural Heritage Community of Practice. This not only allows automatic retrieval of the respective metadata from the IGSN of an archaeological item into TerraLID but also minimises effort if data publication in TerraLID is combined with obtaining IGSNs for the respective samples and objects. 

## NFDI4Objects
The [NFDI4Objects](https://www.nfdi4objects.net/en/) builds the Research Data Infrastructure for the Material Remains of Human History as part of the German effort towards a National Research Data Infrastructure. It is aimed at all members of the scientific community with an interest in material heritage in human and environmental history. The NFDI4Objects develops services and data infrastructures in a community-driven way, including the development of metadata profiles, among others. The TerraLID team is involved in several of its temporary working groups and community clusters. 

## forschungsdaten.info
The webpage [forschungsdaten.info](https://forschungsdaten.info/) is the central information platform about all research data management-related topics for the German-speaking countries. Operated by bwFDM, the State Initiative for Research Data Management in Baden-Württemberg, its editorial board consists of research data management experts from various domains that are based in Germany, Switzerland, and Austria. Beside general information structured along the data life cycle, the page features various articles that provide discipline-specific information about research data management, including [archaeology](https://forschungsdaten.info/wissenschaftsbereiche/archaeologie/) and [geosciences](https://forschungsdaten.info/wissenschaftsbereiche/geowissenschaften/). The page is currently mostly in German with overview articles in English but the editorial board currently works on the extension of the website's English content. 

## Networking Archaeological Data and Communities (2023--2024)
The NEH Institute for Advanced Topics in the Digital Humanities [*Networking Archaeological Data and Communities*](https://alexandriaarchive.org/nadac/) by the Alexandria Archive Institute/Open Context was a series of monthly webinars and two [summer schools](posts/20230730_NADAC.qmd) organised around four semesters devoted to specific themes. It aimed to increase awareness about topics related to research data management among the participants and to build a network among people from the various subfields in archaeology working on research data management-related projects. Three members of the TerraLID core team joined the institute. The institute proved not only very effective in widening and deepening previous knowledge but also in raising awareness on various aspects that are not as prominently featured in German or European discourses as they are in the USA and elsewhere. 
