---
title: "Archive"
---

## Many LIDs, but none matching the vessel 

Developing a community standard for the publication and long-term archiving of lead isotope data in the archaeological sciences -- A brainstorming workshop 

Date: 08--10 February 2023  
Location: German Mining Museum Bochum

### Programme

::: panel-tabset

## Day 1

|9:00|Key talks|
|-----:|:-------------------------------|
|9:00|S. Klein (Bochum): Welcome|
|9:15|S. Klein (Bochum), Th. Rose (Frankfurt), K. Westner (Bochum), Y.-K. Hsu (Bochum): GlobaLID -- Vision of the core team, introduction to the app and discovered challenges|
|9:45|Z. Stos-Gale (Gothenburg): Crossing boundaries: 40 years of lead isotope research in archaeology|
|10:15|F. Albarède (Lyon): Geological/geochemical pitfalls|
|10:45|*Coffee break*|
|11:15|G. Artioli (Padua): Existing lead isotope databases I|
|11:45|S. García di Madinabeitia, J. I. Gil Ibargichi, J. F. Santos (Bilbao): Existing lead isotope databases II|
|12:15|D. Killick (Tuscon, AZ), V. Renson (Columbia, MO), J. Stephens (Columbia, MO): Lead Isotopes on Archaeological Materials in North American Laboratories|
|12:45|D. Berger (Mannheim): Lead isotopes in tin ingots|
|13:15|R. Liu (London): Understanding the social roles of metal in early Chinese Bronze Age: a perspective from highly radiogenic lead|
|13:45|*Lunch break*|
|15:00|D. Wigg-Wolf (Frankfurt a.M.): Application of lead isotopes for provenance studies in numismatics|
|15:30--17:00|Plenary: Current methodological challenges for lead isotopy<br />Existing approaches to a community standard<br />Pro and cons of a community standard|

## Day 2

Round table 1: Which data and meta-information is crucial?

* Introductory talk by I. Villa (Bern): Pb from the millimeter to the planet: what else is usually forgotten?
* Topics:
  a. Analytical data
  b. Geological materials
  c. Artefacts -- and which ones are suitable as reference data?
  d. By-products (e.g., slags, prills, ores from excavation sites)
  
Round table 2: Standardization of databases 

* Introductory talk by K. Elger (Potsdam): t.b.a.
* Topics:
  a. Interconnectivity between different databases: Each group deploys their own data online and develops an API to link other databases. Alternatively, each contributes data to a central database (like GlobaLID) so that all data can be accessed at once?
  b. Unique resource identifier (URI) and controlled vocabularies and terminologies; Adoption of unique identifiers, such as the IGSN for samples. Use of thesauri, ontologies, standardized mineral abbreviations, geological period information from e.g., USGS, EarthChem databases; geological time periods vs. orogenic events. 
  
Round table 3: Statistics and visualization  

* Introductory talk by P. Degryse (Leuven): Perspectives on data dots, biplots, ellipses and model ages
* Additional presentation by T. Eshel (Haifa) and N Yahalom-Mack/D. Finn (Jerusalem)
* Topics:
  a. Visualization, statistic and processing tools, methods -- what is really useful and needed by the community? What is required, what would be nice-to-have?
  b. Reporting -- What is proper reporting? 

## Day 3

9:00--13:00: Morning session

* Impulse talk by Chr. Keller (Berlin): NFDI4Objects
* Presentation of the round table discussions and discussion of their results
* Return to the round tables: Define the discussed standards, taking into account the feedback from the plenary

13:00: Lunch break

14:30 -- 16:00: Afternoon session, final plenary

* Summary of the second round of round tables
* Discussion about how to proceed, e.g., 
  - Follow-up meetings
  - Roadmap to the publication and establishment of the community standard
  - Extension to other methods and materials
  
16:00: Closing of the workshop, take-aways and farewell

:::
