---
title: "Community Kick-Off Meeting on 14 May"

author: 
  - name: Tim Greifelt
    orcid: 0009-0007-9701-8547
date: "2024-06-06"
description: "A short report"

---

The next step is done!

On 14 May, our kick-off meeting took place online to present the progress and the name change from GlobaLID to TerraLID to the community. The offer to participate and exchange ideas was very well received by the up to 40 participants. The aim was to involve the community in the development of TerraLID and to find out what requirements the community has for TerraLID to be able to respond to them specifically in the further development. Thomas Rose presented the TerraLID roadmap in a very vivid presentation and then demonstrated the web app in a simulation. Last but not least, the individual regional editors presented themselves and their work. 

The meeting was a complete success and there was a lot of positive feedback. It was nice to see how much interest there is in TerraLID from the community. 

If you missed the kick-off meeting but would have liked to attend, <!-- you can watch the recorded meeting below --> the recording will become available here soon. 

If you have any questions and/or comments, please send us an [e-mail](mailto:terralid@bergbaumuseum.de). We look forward to hearing from you. 
