---
title: "TerraLID on the road"

author: 
  - name: Thomas Rose
    orcid: 0000-0002-8186-3566
date: "2024-10-27"
description: "Spreading the news about TerraLID"

---

In the second half of 2024, TerraLID was presented at several conferences. 

## European Mineralogical Conference (19--23 August 2024, Dublin)
Every four years, this conference welcomes mineralogists from all European countries and beyond to discuss the newest advances in the field. Traditionally, the conference programme features a session on archaeometry, i.e., the application of mineralogical (and geochemical) methods on cultural heritage materials. Co-convened by me, this session covered a wide-range of topics, including a presentation about the TerraLID project. The presentation was followed up by various questions and discussions in the coffee breaks with colleagues who were seeking advice on how to manage or publish their research data and the advantages of including TerraLID and its prototypes GlobaLID in their resesarch. 

## Annual Meeting of the European Association of Archaeologists (28--31 August 2024, Rome)
The 2024 edition was the 30th edition of this meeting series and marked a new record with more than 5000 participants and 359 sessions. Motivated by the experiences and insights gained while working on TerraLID, I convened the session "Capacity Building for FAIR Data Sharing and Digital Preservation" together Julian Richards (Archaeology Data Service, University of York), Matteo Giaccari (Department of Earth Sciences, Sapienza -- University of Rome), Franco Niccolucci (PIN, University of Florence), and Isabella Ercoles (Department of Earth Sciences, Sapienza -- University of Rome). The session aimed to bring together colleagues from archaeology, the archaeological sciences and research data management to discuss how to increase the flow of data in the field and how to promote the use of research data infrastructures. Many research data infrastructures (RDI) were presented. They can be subdivided into national repositories for archaeological data and material- or method-driven approaches such as Nomisma.org and ArqueoData. The TerraLID project belongs to the second group and was presented as well. In addition, some contributions discussed more general aspects such as the automated creation of maps suitable for people with colour vision deficiencies or how open anthropological data should be accessible. The session was well-received although delays caused by technical difficulties and the overall tight programme left little time for discussion. 

More than other conference, the Annual Meeting of the EAA is always a more than welcome opportunity to meet friends and colleagues from all over Europe. As every year, a personal highlight of the EAA was its social programme with the opening reception at Ex Vigna Barberini on the Palatino and a joyful annual party with live band performing a selection of well-known Italian and international rock and pop songs from the last decades. 

## Verbandstagung der Altertumsverbände (7--10 October 2024, Bochum)
Report Verbandstagung Bochum

## Young Researchers in Archaeometry (15--18 October 2024, Nicosia)
Report YRA2024

## Scientific Forum Entangling Geosciences and Chemistry in Cameroon (24--26 October 2024, Yaoundé)
Report Cameroon
